export const APPLICATION_ACTIONS = {
    SET_APPLICATIONS: "SET_APPLICATIONS",
    ADD_APPLICATIONS: "ADD_APPLICATIONS",
    DELETE_APPLICATION: "DELETE_APPLICATION",
    UPDATE_APPLICATION: "UPDATE_APPLICATION",
    CHANGE_STATUS: "CHANGE_STATUS",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
}